# Site settings
title: iehmltymのBlog
SEOTitle: iehmltymのBlog | ZYY Blog
header-img: img/home-bg.jpg
email: iehmltym@gmail.com
description: "日本のプログラマー@iehmltymの個人ブログ。技術と創造性の融合を探求します。"
keyword: ""iehmltym, テックブログ, プログラミング, 日本, ソフトウェア開発, Web開発, AI, Web,JAVA，Angular，JavaScript, React, React Native"
url: "https://iehmltym.github.io" 
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true
# SNS settings
RSS: false
twitter_username: iehmltym
github_username: iehmltym
qiita_username: iehmltym

# Build settings
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less", "node_modules", "Gruntfile.js", "package.json", "README.md"]
anchorjs: true

# Timezone setting for Japan
timezone: Asia/Tokyo

# Gems
plugins: [jekyll-paginate]

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: iehmltym

# Analytics settings
# Google Analytics
ga_track_id: "UA-XXXXXXXX-X" # Replace with your Google Analytics tracking ID
ga_domain: iehmltym.com

# Sidebar settings
sidebar: true
sidebar-about-description: "クリエイティブなソリューションを追求する日本のソフトウェアエンジニア"
sidebar-avatar: https://github.com/iehmltym.png # Replace with your GitHub profile picture URL

# Featured Tags
featured-tags: true
featured-condition-size: 1

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends: [
  { title: "WU sann", href: "http://wusann.com/" },
 # { title: "Sakura Tanaka", href: "https://sakuratanaka.dev/" },
 # { title: "Hiroshi Sato", href: "http://hiroshisato.jp" },
 # { title: "Yuki Nakamura", href: "https://yukinakamura.me/" },
]
