# Jekyll 站点部署到 GitHub Pages 的工作流配置
name: Deploy Jekyll site to Pages

# 触发条件：main分支推送或手动触发
on:
  push:
    branches: ["main"]
  workflow_dispatch:

# GitHub Token 权限设置
permissions:
  contents: read
  pages: write
  id-token: write

# 并发控制：防止同时运行多个部署
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # 构建任务
  build:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - uses: actions/checkout@v4
      # 配置 Ruby 环境
      - uses: ruby/setup-ruby@4a9ddd6f338a97768b8006bf671dfbad383215f4
        with:
          ruby-version: '3.1'
          bundler-cache: true
          cache-version: 0
      # 配置 GitHub Pages
      - uses: actions/configure-pages@v5
        id: pages
      # 复制音频文件到构建目录
      - name: Copy audio files
        run: |
          mkdir -p _site/assets/audio
          cp -r assets/audio/* _site/assets/audio/ || true
      # 构建 Jekyll 站点
      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production
      # 上传构建产物
      - uses: actions/upload-pages-artifact@v3

  # 部署任务
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # 部署到 GitHub Pages
      - uses: actions/deploy-pages@v4
        id: deployment
```
