# 工作流的名称
name: Ruby Setup and Verification

# 定义触发条件
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify-ruby-setup:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.4'  # 确保这个版本与您的项目需求一致
    
    - name: Verify Ruby installation
      run: |
        ruby --version
        gem --version
        bundle --version
    
    - name: Verify project setup
      run: |
        bundle install
        # 如果您有特定的项目设置验证步骤，可以在这里添加
    
    # 如果您想保留 Linter 检查，可以保留这个步骤
    - name: Run linter
      run: |
        gem install rubocop
        rubocop
